### ISSUE TITLE
NOTICE: qsv repo will be moved to datHere organization on Dec 1, 2024

### ISSUE THREAD

**Issue by jqnatividad** [dathere/qsv#2185]
This repo will be moved to [datHere's GitHub organization](https://github.com/dathere) on Dec 1, 2024.

What started out as a hobby project, has become a critical part of datHere's offerings. 

More datHere staff need access to it to help maintain the project.

**Comment by ondohotola** [comment]
How will this affect the -U autoupdate?

**Comment by jqnatividad** [comment]
Good question @ondohotola. We will add logic in the version just before the move to account for the change.

**Comment by ondohotola** [comment]
thanks

**Comment by jqnatividad** [comment]
As planned, qsv has been moved to the datHere GitHub organization.
