### ISSUE TITLE
qsv joinp --cache-schema Polars error: could not parse `0` as dtype `bool`

### ISSUE THREAD

**Issue by jqnatividad** [dathere/qsv#2369]
### Discussed in https://github.com/dathere/qsv/discussions/2366

<div type='discussions-op-text'>

<sup>Originally posted by **datatraveller1** December 22, 2024</sup>
With `qsv joinp --cache-schema` I get an error:
``Polars error: ComputeError(ErrString("could not parse `0` as dtype `bool` at column 'has_text' ...``
The CSV file has 5 rows and the column `has_text` has the values:
0
1
0
1
1

Is this a bug?

Actually, I don't want to use data types at all. **I want every column simply parsed as "String"**. Is there an option for that?
I use `--cacheschema` because otherwise with big files,  I get even more errors like
``Polars error: ComputeError(ErrString("could not parse `3an` as dtype `i64` at column 'PNM' ...``</div>

**Comment by jqnatividad** [comment]
Hi @datatraveller1, I converted your discussion to an issue.

So it is a bug, as `all_text` is mistakenly inferred as boolean.

Per your suggestion, I refined the `--cache-schema` option so you can explicitly force the schema to all string data types.

**Comment by datatraveller1** [comment]
Hi @jqnatividad, great Thank you!

**Comment by jqnatividad** [comment]
Now that root cause has been fixed in https://github.com/dathere/qsv/commit/cebb6642daf8b528ed8c95be9fc47709abe1c50a @datatraveller1 , you can resume using `--cache-schema 1` to get the performance benefits of doing `joinp` operations with the proper data type, rather than forcing Polars to treat all columns as string.

**Comment by jqnatividad** [comment]
Can you check by compiling from source?

https://github.com/dathere/qsv?tab=readme-ov-file#option-4-compile-from-source

BTW, v2.0.0 is slated to come out today.

**Comment by datatraveller1** [comment]
Hi @jqnatividad Thank you, at the moment compiling form source is too complicated for me. I'll wait until the next binary release.

**Comment by ondohotola** [comment]
With all due respect, if an elderly (retired) Gynecologist can do it, it can’t be too difficult.

On the Mac it’s trivial, on Linux it needs a few tools and libraries via `apt` (#2399) and maybe you should figure it out and hand in a recipe for others to benefit from on Windows.
