### ISSUE TITLE
Package qsv in conda-forge (as done for xsv)

### ISSUE THREAD

**Issue by peterjc** [dathere/qsv#85]
I currently use ``xsv`` installed from conda via the conda-forge community package collection,

https://anaconda.org/conda-forge/xsv
https://github.com/conda-forge/xsv-feedstock/tree/master/recipe

I would like to do the same for ``qsv`` since I increasingly find myself wanting to use functionality only available in this more up to date fork (thank you!).

I am not familiar with rust, but it ought to be straightforward to package ``qsv`` with an almost cut-and-paste copy of that recipe, so I am willing to attempt this having previously contributed recipes for other packages to conda-forge.

**Comment by peterjc** [comment]
WIP at https://github.com/conda-forge/staged-recipes/pull/16513

**Comment by peterjc** [comment]
Not entirely stale, still work happening on https://github.com/conda-forge/staged-recipes/pull/16595 - but the macOS builds are proving tricky.

**Comment by holtgrewe** [comment]
@jqnatividad I see that this is closed on the conda-forge side again. Could we maybe merge this in conda-forge without th epython feature?

**Comment by peterjc** [comment]
If the optional Python bits were the only thing blocking the conda-forge build, I'd second that as an occasional user of qsv.

**Comment by jqnatividad** [comment]
@holtgrewe @peterjc thanks for your interest.

I'm reopening this issue and target to have the next release, if not the upcoming 0.113.0 packaged for conda-forge.

**Comment by holtgrewe** [comment]
@jqnatividad thanks!

**Comment by jqnatividad** [comment]
Hi @peterjc , @holtgrewe ,

I tried amending the qsv recipe but I'm not that familiar with conga-forge, perhaps, you can give it a try?

https://github.com/jqnatividad/staged-recipes/tree/qsv/recipes/qsv

**Comment by jqnatividad** [comment]
Still interested in supporting this, but I'm afraid I don't know much about conda-forge packaging, so will have to lean on contributors...

**Comment by holtgrewe** [comment]
Thanks for your interest, @jqnatividad. Could I have your comment on this point here?

https://github.com/conda-forge/staged-recipes/pull/24556#issuecomment-1823112222

**Comment by holtgrewe** [comment]
@jqnatividad did you already have a chance to have another look?

**Comment by apcamargo** [comment]
It seems that the Conda package [hasn't been updated in a while](https://github.com/conda-forge/qsv-feedstock/pulls?q=sort%3Aupdated-desc+is%3Apr+is%3Aopen). @danielnachun, any idea of what is blocking the build?

**Comment by peterjc** [comment]
We had a lot of trouble getting this to build on conda in the first place (even though xsv had worked). I missed there was yet another attempt in https://github.com/conda-forge/staged-recipes/pull/27064 which was merged in August 2024.

It looks like the recent automated updates failed, at least once of the blocking issues looks to have been fixed now though - https://github.com/conda-forge/rust-feedstock/issues/204

Anyway, closing since qsv is now in conda-forge, and quite a recent version too - I can drop using xsv now 🚀

**Comment by danielnachun** [comment]
I will follow up with this in the feedstock - part of the blocker to updating has been that I had issues getting cross-compilation working, but there seem to some other problems as well.  I think I know how to fix the Python 3.13 build though so I'll push that at least.
